package exercicio02;

/**
 * Each new term in the Fibonacci sequence is generated by 
 * adding the previous two terms. By starting with 1 and 2, 
 * the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values 
* do not exceed four million, find the sum of the even-valued terms.
 */
public class Metodo {
    int i = 1;
    int j = 0;
    
    
    
    public void fibo(){
         
            
        int fibo = 1, soma = 0;
        
        for (int k =0;fibo <4000000; k++) {
            System.out.println("J: "+ fibo);
            
            i = i+j;
            j = i -j;
        
            fibo = i+j;  
            if(fibo%2 ==0)
            soma = soma+fibo; 
            
        }
        System.out.println(soma);
         }

}
