
/*
Each new term in the Fibonacci sequence is generated by adding the 
previous two terms. By starting with 1 and 2, the first 10 terms will be:*/
public class problem02 {
    public static void main(String[] args) {
        System.out.println("====================================================");
        System.out.println("            SEQUENCIA DE FIBONACCI");
        System.out.println("====================================================");
        
        int aux = 0;
        int a = 1;
        int b = 0;
        
        for (int i = 0; i < 4000000; i++) {
            a = a+b;
            b = a-b;
            aux = a+b; 
            System.out.println(aux);
            }
            System.out.println(aux);
            
                 
    
        }
    
                
    }


